DROP TABLE IF EXISTS T_USER ; 
CREATE TABLE T_USER (
	USER_ID VARCHAR(100) PRIMARY KEY , 
    USER_PW VARCHAR(100) , 
	SI VARCHAR(100) , 
    GU VARCHAR(100) , 
    DONG VARCHAR(100) 
) ; 

DROP TABLE IF EXISTS T_USER_TOKEN ; 
CREATE TABLE T_USER_TOKEN (
	USER_ID VARCHAR(100) , 
	USER_TOKEN VARCHAR(100) ,
	PRIMARY KEY ( USER_ID , USER_TOKEN )
) ; 

DROP TABLE IF EXISTS T_INTEREST ; 
CREATE TABLE T_INTEREST (
	INTEREST_ID VARCHAR(100) PRIMARY KEY , 
    INTEREST_NAME VARCHAR(1000) 
);

DROP TABLE IF EXISTS T_USER_INTEREST ; 
CREATE TABLE T_USER_INTEREST ( 
	USER_ID VARCHAR(100) ,
    INTEREST_ID VARCHAR(100) ,
    PRIMARY KEY ( USER_ID , INTEREST_ID )
);
    
    