--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER ; 
CREATE TABLE T_USER (
	USER_ID VARCHAR(100) PRIMARY KEY , 
    USER_PW VARCHAR(100) NOT NULL ,
    USER_NAME VARCHAR(100) NOT NULL , 
    USER_NICKNAME VARCHAR(100) NOT NULL , 
	USER_SI VARCHAR(100) NULL , 
    USER_GU VARCHAR(100) NULL , 
    USER_DONG VARCHAR(100) NULL ,
    REGIST_DATE TIMESTAMP NULL ,
    UPDATE_DATE TIMESTAMP NULL ,
    DELETE_AT VARCHAR(1) DEFAULT 'N' , 
    DELETE_DATE TIMESTAMP NULL 
) ; 
ALTER TABLE T_USER CONVERT TO CHARACTER SET UTF8;

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_TOKEN ; 
CREATE TABLE T_USER_TOKEN (
	USER_ID VARCHAR(100) NOT NULL , 
    USER_TOKEN VARCHAR(100) NOT NULL ,
    REGIST_DATE TIMESTAMP NULL ,
    PRIMARY KEY ( USER_ID , USER_TOKEN )
) ; 
ALTER TABLE T_USER_TOKEN CONVERT TO CHARACTER SET UTF8;

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_FRIEND ; 
CREATE TABLE T_USER_FRIEND (
	USER_ID VARCHAR(100) , 
	FRIEND_ID VARCHAR(100) , 
	FRIEND_NICKNAME VARCHAR(500) , 
	REGIST_DATE TIMESTAMP ,
	UPDATE_DATE TIMESTAMP , 
	PRIMARY KEY ( USER_ID , FRIEND_ID )
);
ALTER TABLE T_USER_FRIEND CONVERT TO CHARACTER SET UTF8;  

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_GROUP ; 
CREATE TABLE T_USER_GROUP (
	USER_ID VARCHAR(100) NOT NULL , 
	GROUP_ID VARCHAR(100) NOT NULL , 
	GROUP_NICKNAME VARCHAR(500) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL ,
	UPDATE_DATE TIMESTAMP NULL , 
	PRIMARY KEY ( USER_ID , GROUP_ID )
);
ALTER TABLE T_USER_GROUP CONVERT TO CHARACTER SET UTF8;  

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_GROUP ; 
CREATE TABLE T_GROUP (
	GROUP_ID VARCHAR(100) PRIMARY KEY ,
	GROUP_NAME VARCHAR(500) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL , 
	UPDATE_DATE TIMESTAMP NULL 
);
ALTER TABLE T_GROUP CONVERT TO CHARACTER SET UTF8;  

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_CATEGORY ; 
CREATE TABLE T_CATEGORY (
	CATEGORY_ID VARCHAR(100) NOT NULL ,
	UPPER_CATEGORY_ID VARCHAR(100) NOT NULL , 
	CATEGORY_NAME VARCHAR(500) NOT NULL , 
	CATEGORY_LEVEL INTEGER(11) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL , 
	UPDATE_DATE TIMESTAMP NULL ,
	DELETE_AT VARCHAR(1) DEFAULT 'N' , 
	DELETE_DATE TIMESTAMP ,
	PRIMARY KEY ( CATEGORY_ID , UPPER_CATEGORY_ID )
);
ALTER TABLE T_CATEGORY CONVERT TO CHARACTER SET UTF8;  

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_CATEGORY ; 
CREATE TABLE T_USER_CATEGORY ( 
	USER_ID VARCHAR(100) NOT NULL , 
	CATEGORY_ID VARCHAR(100) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL ,
	PRIMARY KEY (USER_ID , CATEGORY_ID )
) ; 
ALTER TABLE T_USER_CATEGORY CONVERT TO CHARACTER SET UTF8; 

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_IGNORE ; 
CREATE TABLE T_USER_IGNORE ( 
	USER_ID VARCHAR(100) NOT NULL , 
	IGNORE_ID VARCHAR(100) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL ,
	PRIMARY KEY (USER_ID , IGNORE_ID )
) ; 
ALTER TABLE T_USER_IGNORE CONVERT TO CHARACTER SET UTF8; 

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_USER_FOLLOW ; 
CREATE TABLE T_USER_FOLLOW ( 
	USER_ID VARCHAR(100) NOT NULL , 
	FOLLOW_ID VARCHAR(100) NOT NULL , 
	REGIST_DATE TIMESTAMP NULL ,
	PRIMARY KEY (USER_ID , FOLLOW_ID )
) ; 
ALTER TABLE T_USER_FOLLOW CONVERT TO CHARACTER SET UTF8;

--------------------------------------------------------------------------
DROP TABLE IF EXISTS T_FEED ; 
CREATE TABLE T_FEED (
	FEED_ID VARCHAR(100) NOT NULL , 
	REGIST_USER_ID VARCHAR(100) ,
	FEED_TITLE VARCHAR(1000), 
	FEED_TEXT VARCHAR(4000) , 
	REGIST_DATE TIMESTAMP NULL , 
	UPDATE_DATE TIMESTAMP NULL ,
	DELETE_AT VARCHAR(1) DEFAULT 'N',
	DELETE_DATE TIMESTAMP , 
	PRIMARY KEY ( FEED_ID , REGIST_USER_ID )
) ; 
ALTER TABLE T_FEED CONVERT TO CHARACTER SET UTF8;